### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wilsmex** [JamesHemery/Cake3Cart#1]
I know this is brand new, but could you add some basic docs/configs on getting up and running with your plugin to the readme?

**Comment by JamesHemery** [comment]
Hello,

Sorry for the late response. In the **next days**, the **documentation should arrive** as well as some modifications and a small **REST API** to manage the shopping carts.

I invite you to follow this repository !
Thanks.

**Comment by wilsmex** [comment]
Sounds good.  I've got the plugin working as a component, and found an issue or two.  I'll wait for the update to play some more.

**Comment by JamesHemery** [comment]
Ok thank you. Also, I will rework the coupon codes system because it's not great. The update comes in the weekend !

**Comment by JamesHemery** [comment]
Sorry, I was late on the update. The code is finished, I have only to write the documentation. I push as soon as possible.

**Comment by JamesHemery** [comment]
I push the latest version of the plugin in the commit #e387ed9. I still have to write the documentation but you can already use the plugin. 

_I am sorry for the update time, however this plugin advances at the same time as a client._

**Comment by wilsmex** [comment]
Thanks!  Looks good.  Quite a few changes from the previous method.  I found one issue with the "Cart.beforeSetItemQuantity" event.  The second should be "Cart.afterSetItemQuantity".

I'm not too familiar with Cake's events (which you've moved to), so could you give me some basic code to get started to handle the "Cart.applyTaxRules" event?

Thanks

**Comment by JamesHemery** [comment]
Thank you to have reporting the problem, i've solved that.

**Here's how to apply a tax:**
In this example I apply 20% VAT on the basket.
The **"&" before $amount** is important to take into account the changes effected during the event.

```php
$this->eventManager()->on('Cart.applyTaxRules', function($event, $items, **&$amount**) use ($session){
    $amount['total']['incl_tax'] = $amount['total']['excl_tax'] * (1 + 20 / 100);
});
```
