### ISSUE TITLE
Améliorations à apporter

### ISSUE THREAD

**Issue by Gynidark** [JamesHemery/Cake3Cart#2]
Bonjour @JamesHemery,

Après avoir fait le tour sur le dépôt, j'ai effectivement vu quelques améliorations à réaliser afin d'avoir une librairie correcte.

- Correction de la faute **LICENCE** en **LICENSE**. 
- Ajouter le lien de la license dans le paragraphe **LICENSE** [ici](https://github.com/JamesHemery/Cake3Cart#licence).
- Ajouter des badges en haut du README.md(tel que la version de CakePHP et la licence).
- Évite les [commits](https://github.com/JamesHemery/Cake3Cart/commits/master) incompréhensible, c'est beaucoup mieux et beau en ayant des commits compréhensibles.
- Ajouter dans ce [fichier](https://github.com/JamesHemery/Cake3Cart/blob/master/src/Model/Entity/Coupon.php) le phpdoc au dessus des fonctions.
- Ajouter [Babel](https://babeljs.io) pour compiler ton JavaScript ES6 en ES5 afin d'avoir la compatibilité sur les navigateurs.

Il serait sympa aussi d'avoir un petit screenshot de ce que tu as comme résultat à la fin aussi afin de ne pas être dans l'inconnu. :wink:

Au niveau du code, je n'ai vraiment rien à dire mise à part le **phpdoc** mais ça arrive d'oublier.  Bien entendu, les améliorations à apporter sont de mon point de vu. À toi d'en prendre compte ou non. :simple_smile:

Cordialement,
Gynidark.

**Comment by JamesHemery** [comment]
Bonjour @Gynidark,

Merci beaucoup pour ton retour, j'effectuerais les changements sous peu. Il faut également que j'ajoute quelques fonctionnalités.
